baseURL = 'https://sniteesh.com/'
languageCode = 'en-us'
title = 'Sai Niteesh Ganga'
theme = 'anatole'
disableFastRender = true

[params]
title = "Sai Niteesh Ganga"
author = "Sai Niteesh Ganga"
description = "Software Engineer | Cloud Enthusiast | Tech Blogger"
profilePicture = 'images/profile.jpeg'
copyright = "2025 [Sai Niteesh Ganga](/)"
reversepagetitle = true
favicon = "favicons/"

[[menu.main]]
name = "Blogs"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 2

[[menu.main]]
name = "Diet Tracker"
url = "/diet-tracker/"
weight = 3
